### ISSUE TITLE
License missing everywhere

### ISSUE THREAD

**Issue by FSharpCSharp** [rdrrichards/QIQO.Business.Client.Solution#17]
I think these projects are great for learning how to run good software architecture. There are rarely such coherent examples as this. Unfortunately, I can't find a license under which all this runs anywhere. Also with the dependent projects I find unfortunately none. So I ask the question under which license the application runs, including the dependencies. Something like MIT would be desirable, because you could reuse many parts of this framework.

**Comment by rdrrichards** [comment]
I guess I never really thought about licensing on this repo. Still surprises me that some have found it, forked it, and now commented on it. I have added the MIT license to the repo. Seems like that should be a good one to go with.

I don't know how active I will be with this repo. I have other repos that I am trying to focus on.

Feel free to use. There are parts of this that could use refining.

Keep any expectations around support to a minimum.

**Comment by FSharpCSharp** [comment]
Many thanks for the detailed answer! I also came across the repo more or less by accident when I was looking for examples of Prism. The examples provided by Microsoft are very poor, and there is nothing reasonable about database connectivity. Your example here has everything you need for a big application, and it's impressive! You have done a preliminary work which is very useful for many, and also saves a lot of time. It's a shame that you had to reinvent a lot of things and Microsoft doesn't provide similar templates. But well, there's nothing you can do.
